<table class="table table-bordered table-striped table-vcenter js-dataTable-full">
                            <thead>
                                <tr>
                                    <th>Tipo</th>
                                    <th class="d-none d-sm-table-cell">Cantidad</th>
                                    <th class="d-none d-sm-table-cell">Fecha</th>
                                </tr>
                            </thead>
                            <tbody>

                                <tr>
                                    <td>Abono</td>
                                    <td>1000</td>
                                    <td>10/10/2020</td>
                                </tr>
                                <tr>
                                    <td>Abono</td>
                                    <td>1000</td>
                                    <td>10/10/2020</td>
                                </tr>
                                <tr>
                                    <td>Abono</td>
                                    <td>1000</td>
                                    <td>10/10/2020</td>
                                </tr>
                                <tr>
                                    <td>Abono</td>
                                    <td>1000</td>
                                    <td>10/10/2020</td>
                                </tr>
                                <tr>
                                    <td>Abono</td>
                                    <td>1000</td>
                                    <td>10/10/2020</td>
                                </tr>
                                <tr>
                                    <td>Abono</td>
                                    <td>1000</td>
                                    <td>10/10/2020</td>
                                </tr>
                                <tr>
                                    <td>Abono</td>
                                    <td>1000</td>
                                    <td>10/10/2020</td>
                                </tr>
                                <tr>
                                    <td>Abono</td>
                                    <td>1000</td>
                                    <td>10/10/2020</td>
                                </tr>
                                <tr>
                                    <td>Abono</td>
                                    <td>1000</td>
                                    <td>10/10/2020</td>
                                </tr>
                                <tr>
                                    <td>Abono</td>
                                    <td>1000</td>
                                    <td>10/10/2020</td>
                                </tr>
                                <tr>
                                    <td>Abono</td>
                                    <td>1000</td>
                                    <td>10/10/2020</td>
                                </tr>
                                <tr>
                                    <td>Abono</td>
                                    <td>1000</td>
                                    <td>10/10/2020</td>
                                </tr>
                                <tr>
                                    <td>Abono</td>
                                    <td>1000</td>
                                    <td>10/10/2020</td>
                                </tr>
                                <tr>
                                    <td>Abono</td>
                                    <td>1000</td>
                                    <td>10/10/2020</td>
                                </tr>

                            </tbody>
                        </table>